export const ROLE_DEFINITIONS = [
  {
    name: "SUPER_ADMIN",
    label: "Super Admin",
    permissions: "*",
  },
  {
    name: "ADMIN",
    label: "Admin",
    permissions: [
      ["dashboard", "read"],
      ["product", "create"],
      ["product", "read"],
      ["product", "update"],
      ["product", "delete"],
      ["category", "read"],
      ["category", "create"],
      ["category", "update"],
      ["category", "delete"],
      ["subcategory", "read"],
      ["subcategory", "create"],
      ["subcategory", "update"],
      ["subcategory", "delete"],
      ["lead", "read"],
      ["lead", "update"],
      ["order", "read"],
      ["order", "update"],
      ["seo", "read"],
      ["seo", "update"],
      ["setting", "read"],
      ["setting", "update"],
      ["user", "read"],
      ["role", "read"],
      ["permission", "read"],
      ["gallery", "read"],
      ["testimonial", "read"],
      ["industry", "read"],
    ],
  },
  {
    name: "MANAGER",
    label: "Manager",
    permissions: [
      ["dashboard", "read"],
      ["product", "read"],
      ["product", "create"],
      ["product", "update"],
      ["category", "read"],
      ["subcategory", "read"],
      ["lead", "read"],
      ["lead", "update"],
      ["order", "read"],
      ["seo", "read"],
    ],
  },
  {
    name: "EDITOR",
    label: "Editor",
    permissions: [
      ["dashboard", "read"],
      ["product", "read"],
      ["product", "update"],
      ["category", "read"],
      ["subcategory", "read"],
      ["seo", "read"],
      ["seo", "update"],
      ["gallery", "read"],
      ["testimonial", "read"],
      ["industry", "read"],
    ],
  },
];

export const PERMISSIONS = [
  ["dashboard", "read"],
  ["product", "create"],
  ["product", "read"],
  ["product", "update"],
  ["product", "delete"],
  ["category", "create"],
  ["category", "read"],
  ["category", "update"],
  ["category", "delete"],
  ["subcategory", "create"],
  ["subcategory", "read"],
  ["subcategory", "update"],
  ["subcategory", "delete"],
  ["variant", "create"],
  ["variant", "read"],
  ["variant", "update"],
  ["variant", "delete"],
  ["attribute", "create"],
  ["attribute", "read"],
  ["attribute", "update"],
  ["attribute", "delete"],
  ["industry", "create"],
  ["industry", "read"],
  ["industry", "update"],
  ["industry", "delete"],
  ["gallery", "create"],
  ["gallery", "read"],
  ["gallery", "update"],
  ["gallery", "delete"],
  ["testimonial", "create"],
  ["testimonial", "read"],
  ["testimonial", "update"],
  ["testimonial", "delete"],
  ["seo", "read"],
  ["seo", "update"],
  ["setting", "read"],
  ["setting", "update"],
  ["lead", "read"],
  ["lead", "update"],
  ["order", "read"],
  ["order", "update"],
  ["user", "read"],
  ["user", "create"],
  ["user", "update"],
  ["user", "delete"],
  ["role", "read"],
  ["role", "create"],
  ["role", "update"],
  ["role", "delete"],
  ["permission", "read"],
];

